package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Overthink Material 3 Light Theme Colors (design.md)
val LightPrimary = Color(0xFFB84F7A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFF4D6E2)
val LightOnPrimaryContainer = Color(0xFF4A122D)
val LightSecondary = Color(0xFF654334)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFF4E2D8)
val LightOnSecondaryContainer = Color(0xFF2A150B)
val LightTertiary = Color(0xFF536925)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD7E9AD)
val LightOnTertiaryContainer = Color(0xFF182900)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF8F3EF)
val LightOnBackground = Color(0xFF241F20)
val LightSurface = Color(0xFFFFFDFC)
val LightOnSurface = Color(0xFF241F20)
val LightSurfaceVariant = Color(0xFFEEE7E2)
val LightOnSurfaceVariant = Color(0xFF554C4D)
val LightSurfaceTint = Color(0xFFB84F7A)
val LightSurfaceDim = Color(0xFFDED8D4)
val LightSurfaceBright = Color(0xFFFFF9F7)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF7F1ED)
val LightSurfaceContainer = Color(0xFFF1EAE5)
val LightSurfaceContainerHigh = Color(0xFFEBE4DF)
val LightSurfaceContainerHighest = Color(0xFFE6DFDA)
val LightOutline = Color(0xFF817375)
val LightOutlineVariant = Color(0xFFD5C5C8)
val LightInverseSurface = Color(0xFF382E31)
val LightInverseOnSurface = Color(0xFFFFEBF0)
val LightInversePrimary = Color(0xFFFFB0CC)
val LightScrim = Color(0xFF000000)

// Overthink Material 3 Dark Theme Colors (design.md)
val DarkPrimary = Color(0xFFFFB0CC)
val DarkOnPrimary = Color(0xFF640037)
val DarkPrimaryContainer = Color(0xFF86114F)
val DarkOnPrimaryContainer = Color(0xFFFFD8E7)
val DarkSecondary = Color(0xFFEFC0AB)
val DarkOnSecondary = Color(0xFF472A1C)
val DarkSecondaryContainer = Color(0xFF60402F)
val DarkOnSecondaryContainer = Color(0xFFFFDBC9)
val DarkTertiary = Color(0xFFBCD584)
val DarkOnTertiary = Color(0xFF293600)
val DarkTertiaryContainer = Color(0xFF3E510D)
val DarkOnTertiaryContainer = Color(0xFFD7F2A1)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1C191A)
val DarkOnBackground = Color(0xFFF9F3F0)
val DarkSurface = Color(0xFF282324)
val DarkOnSurface = Color(0xFFF9F3F0)
val DarkSurfaceVariant = Color(0xFF514347)
val DarkOnSurfaceVariant = Color(0xFFD7C1C7)
val DarkSurfaceTint = Color(0xFFFFB0CC)
val DarkSurfaceDim = Color(0xFF141213)
val DarkSurfaceBright = Color(0xFF463F41)
val DarkSurfaceContainerLowest = Color(0xFF0F0D0E)
val DarkSurfaceContainerLow = Color(0xFF211D1E)
val DarkSurfaceContainer = Color(0xFF2D2729)
val DarkSurfaceContainerHigh = Color(0xFF383133)
val DarkSurfaceContainerHighest = Color(0xFF433C3E)
val DarkOutline = Color(0xFFA08C92)
val DarkOutlineVariant = Color(0xFF514347)
val DarkInverseSurface = Color(0xFFF9F3F0)
val DarkInverseOnSurface = Color(0xFF382E2F)
val DarkInversePrimary = Color(0xFFB84F7A)
val DarkScrim = Color(0xFF000000)

// Data Visualisation Colours (design.md)
val ChartSunLight = Color(0xFFC79012)
val ChartSunDark = Color(0xFFE9C768)
val ChartSageLight = Color(0xFF71843D)
val ChartSageDark = Color(0xFFBCD584)
val ChartPeriwinkleLight = Color(0xFF7185BC)
val ChartPeriwinkleDark = Color(0xFFBBC9F0)
val ChartCocoaLight = Color(0xFF654334)
val ChartCocoaDark = Color(0xFFD7B59D)


